"use client";
import './globals.css'
import { Inter } from 'next/font/google'
import Image from "next/image";
import DataProvider from '@/contexts/data';

const inter = Inter({ subsets: ['latin'] })

//theme
import "primereact/resources/themes/lara-light-indigo/theme.css";
//core
import "primereact/resources/primereact.min.css";
//icons
// import "primeicons/primeicons.css";

import { detectLocale, navigatorDetector } from "typesafe-i18n/detectors";
import { loadLocale } from "@/i18n/i18n-util.sync";
import { baseLocale, locales } from "@/i18n/i18n-util";
import TypesafeI18n from "@/i18n/i18n-react";
import PreSettingsProvider from '@/contexts/pre-settings';


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  let locale = baseLocale; // default to baseLocale
  if (typeof window !== "undefined") {
    // Check if window is defined to ensure running on client side
    locale = detectLocale(baseLocale, locales, navigatorDetector);
    loadLocale(locale);
  }

  return (
    <TypesafeI18n locale={locale}>
      <DataProvider>
        <PreSettingsProvider>
          <html lang="en">
            <body className={inter.className}>
              <div className="flex flex-col lg:flex-row gap-10 lg:gap-8 justify-start items-center lg:justify-center lg:items-start h-screen bg-dmun text-black p-4 pt-10 lg:p-8 lg:pt-8 overflow-scroll">
                <div className="flex flex-row justify-center items-center gap-3 lg:sticky lg:top-0 lg:left-0">
                  <Image
                    src="/logo.png"
                    alt="Logo"
                    width={150}
                    height={150}
                  />
                </div>
                <div className="flex-1 flex flex-col justify-start gap-3 items-center p-4 rounded-md bg-white w-full max-w-5xl shadow-lg">
                  {children}
                </div>
              </div>
            </body>
          </html>
        </PreSettingsProvider>
      </DataProvider>
    </TypesafeI18n >
  )
}
